name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # リポジトリのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # Node.jsのセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 必要なパッケージのインストール
      - name: Install dependencies
        run: |
          cd web
          npm i

      # アプリケーションのビルド
      - name: Build project
        run: |
          cd web
          npm run build

      # アーティファクトのアップロード
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./web/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # GitHub Pagesへのデプロイ
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
